# Generated by Django 5.1.7 on 2025-06-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounters',
            name='active',
            field=models.BooleanField(default=True, help_text='If false, the encounter will not be shown to users'),
        ),
        migrations.AlterField(
            model_name='encounters',
            name='translations',
            field=models.JSONField(default=dict, help_text='Needs to be in Form: {"de-de":{"name":content, "text":content}} - DO NOT LET USER CHANGE THESE WITHOUT VERIFICATION'),
        ),
    ]
